from datetime import date, datetime, timezone

from fastapi import APIRouter

from server.schemas import DashboardResponse, DashboardTotals, ProductStock

router = APIRouter()


@router.get("/dashboard", response_model=DashboardResponse)
def get_dashboard() -> DashboardResponse:
    """Hardcoded stock position. Swapped for a Lakebase query on Wednesday."""
    return DashboardResponse(
        generated_at=datetime.now(timezone.utc),
        totals=DashboardTotals(
            revenue_7d=17837,
            units_sold_7d=383,
            needs_order_count=5,
            dead_stock_count=3,
        ),
        products=[
            ProductStock(
                product_id="P001",
                name="Maruti Swift VXi",
                category="Hatchback",
                qty_on_hand=24,
                avg_daily_sales_7d=11.4,
                days_of_cover=2.1,
                lead_time_days=1,
                suggested_order_qty=60,
                stock_expiry_date=date(2026, 8, 13),
                revenue_7d=1140,
                status="low",
            ),
            ProductStock(
                product_id="P002",
                name="Hyundai i20 Asta",
                category="Hatchback",
                qty_on_hand=18,
                avg_daily_sales_7d=5.6,
                days_of_cover=3.2,
                lead_time_days=1,
                suggested_order_qty=30,
                stock_expiry_date=date(2026, 8, 14),
                revenue_7d=728,
                status="low",
            ),
            ProductStock(
                product_id="P003",
                name="Tata Altroz XZ",
                category="Hatchback",
                qty_on_hand=22,
                avg_daily_sales_7d=5.4,
                days_of_cover=4.1,
                lead_time_days=1,
                suggested_order_qty=40,
                stock_expiry_date=date(2026, 8, 16),
                revenue_7d=660,
                status="low",
            ),
            ProductStock(
                product_id="P004",
                name="Mahindra Thar LX",
                category="SUV",
                qty_on_hand=32,
                avg_daily_sales_7d=8.0,
                days_of_cover=4.0,
                lead_time_days=5,
                suggested_order_qty=80,
                stock_expiry_date=None,
                revenue_7d=1520,
                status="must_order_today",
            ),
            ProductStock(
                product_id="P005",
                name="Toyota Fortuner 4x4",
                category="SUV",
                qty_on_hand=12,
                avg_daily_sales_7d=2.4,
                days_of_cover=5.0,
                lead_time_days=6,
                suggested_order_qty=30,
                stock_expiry_date=None,
                revenue_7d=3480,
                status="must_order_today",
            ),
            ProductStock(
                product_id="P006",
                name="Honda City VX",
                category="Sedan",
                qty_on_hand=26,
                avg_daily_sales_7d=3.2,
                days_of_cover=8.1,
                lead_time_days=4,
                suggested_order_qty=24,
                stock_expiry_date=None,
                revenue_7d=3808,
                status="ok",
            ),
            ProductStock(
                product_id="P007",
                name="Kia Seltos HTX",
                category="SUV",
                qty_on_hand=14,
                avg_daily_sales_7d=2.8,
                days_of_cover=5.0,
                lead_time_days=2,
                suggested_order_qty=20,
                stock_expiry_date=date(2026, 8, 12),
                revenue_7d=1092,
                status="expiring",
            ),
            ProductStock(
                product_id="P008",
                name="Tata Nexon EV Max",
                category="SUV",
                qty_on_hand=9,
                avg_daily_sales_7d=1.1,
                days_of_cover=8.2,
                lead_time_days=3,
                suggested_order_qty=12,
                stock_expiry_date=date(2026, 8, 15),
                revenue_7d=1155,
                status="expiring",
            ),
            ProductStock(
                product_id="P009",
                name="Renault Kwid RXL",
                category="Hatchback",
                qty_on_hand=48,
                avg_daily_sales_7d=4.2,
                days_of_cover=11.4,
                lead_time_days=3,
                suggested_order_qty=0,
                stock_expiry_date=None,
                revenue_7d=235,
                status="ok",
            ),
            ProductStock(
                product_id="P010",
                name="Maruti Baleno Zeta",
                category="Hatchback",
                qty_on_hand=30,
                avg_daily_sales_7d=4.8,
                days_of_cover=6.3,
                lead_time_days=3,
                suggested_order_qty=24,
                stock_expiry_date=None,
                revenue_7d=1848,
                status="ok",
            ),
            ProductStock(
                product_id="P011",
                name="Skoda Slavia Style",
                category="Sedan",
                qty_on_hand=26,
                avg_daily_sales_7d=3.6,
                days_of_cover=7.2,
                lead_time_days=3,
                suggested_order_qty=18,
                stock_expiry_date=None,
                revenue_7d=1170,
                status="ok",
            ),
            ProductStock(
                product_id="P012",
                name="Toyota Innova Crysta",
                category="MPV",
                qty_on_hand=20,
                avg_daily_sales_7d=1.4,
                days_of_cover=14.3,
                lead_time_days=4,
                suggested_order_qty=0,
                stock_expiry_date=None,
                revenue_7d=546,
                status="ok",
            ),
            ProductStock(
                product_id="P013",
                name="Jeep Compass Limited",
                category="SUV",
                qty_on_hand=34,
                avg_daily_sales_7d=0.3,
                days_of_cover=113.3,
                lead_time_days=4,
                suggested_order_qty=0,
                stock_expiry_date=date(2026, 11, 20),
                revenue_7d=168,
                status="dead",
            ),
            ProductStock(
                product_id="P014",
                name="Citroen C3 Shine",
                category="Hatchback",
                qty_on_hand=28,
                avg_daily_sales_7d=0.2,
                days_of_cover=140.0,
                lead_time_days=5,
                suggested_order_qty=0,
                stock_expiry_date=None,
                revenue_7d=182,
                status="dead",
            ),
            ProductStock(
                product_id="P015",
                name="Nissan Magnite XV",
                category="SUV",
                qty_on_hand=30,
                avg_daily_sales_7d=0.3,
                days_of_cover=100.0,
                lead_time_days=3,
                suggested_order_qty=0,
                stock_expiry_date=date(2026, 12, 5),
                revenue_7d=105,
                status="dead",
            ),
        ],
    )
